# Generated by Django 5.1.3 on 2024-11-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotlinApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
            ],
        ),
    ]
