# Generated by Django 5.1.3 on 2024-11-14 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kotlinApp', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
