# Generated by Django 5.1.3 on 2024-11-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kotlinApp', '0004_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='datetime',
            new_name='dateTime',
        ),
    ]
